image: stangirard/serverless:latest

stages:
  - deploy
  
deploy:
  stage: deploy
  image: docker:19.03
  services:
    - name: docker:19.03-dind
  before_script:
    - docker build --network=host --build-arg RELEASE="$RELEASE" -t stangirard/serverless .
    - docker tag stangirard/serverless:latest stangirard/serverless:"$RELEASE"
  script:
    - docker push stangirard/serverless:latest;
    - docker push stangirard/serverless:"$RELEASE";
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: 'tcp://localhost:2375' 
    RELEASE: 2.12.0

