image: docker:latest

stages:
  - deploy
  
deploy:
  stage: deploy
  services:
    - name: docker:dind
  before_script:
    - docker build --build-arg RELEASE="$RELEASE" -t stangirard/serverless .
    - docker tag stangirard/serverless:latest stangirard/serverless:"$RELEASE"
  script:
    - echo "$DOCKER_PASS" | docker login --username "$DOCKER_USER" --password-stdin
    - docker push stangirard/serverless:latest;
    - docker push stangirard/serverless:"$RELEASE";
  variables:
    RELEASE: 2.13.0
